<?php
/**
 * This file is part of the woo-poly-integration plugin.
 * Original (c) Hyyan Abo Fakher <hyyanaf@gmail.com>.
 * Modernized fork (c) IntegrIT Solutions.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
namespace Hyyan\WPI;

use Hyyan\WPI\Product\Variation;
use Hyyan\WPI\Product\Meta;
use Hyyan\WPI\Utilities;

/**
 * Cart.
 *
 * Handle cart translation
 *
 * @author Hyyan Abo Fakher <hyyanaf@gmail.com>
 */
class Cart
{

    const ADD_TO_CART_HANDLER_VARIABLE = 'wpi_variable';

    /**
     * Construct object.
     */
    public function __construct()
    {
        // Dedupe on add-to-cart for CLASSIC add path (shortcode pages, AJAX from
        // single-product page): swap the product ID to the canonical cart-line
        // product ID if a translation of the same logical product is already in
        // the cart. This filter is NOT applied by the Store API add path — see
        // `dedupeStoreApiAdd()` for the Block cart equivalent.
        add_filter('woocommerce_add_to_cart_product_id', array($this, 'addToCart'), 10, 1);

        // Dedupe on add-to-cart for STORE API (Block cart) path. WC 8.8+ exposes
        // this filter to mutate add-to-cart request data BEFORE `generate_cart_id`
        // runs. Without this, a German variant of an already-in-cart English
        // product would create a second cart line under Block cart, with no
        // dedup — verified in WC 10.7 source:
        //   src/StoreApi/Routes/V1/CartAddItem.php:116
        //   src/StoreApi/Utilities/CartController.php:99-147 (add_to_cart)
        add_filter('woocommerce_store_api_add_to_cart_data', array($this, 'dedupeStoreApiAdd'), 10, 2);
        add_filter('rest_request_before_callbacks', array($this, 'dedupeStoreApiCartItemsRoute'), 10, 3);

        // ROOT-CAUSE TRANSLATION (Phase C): swap the cart item's product reference
        // at session-load and add-to-cart time. This means by the time downstream
        // consumers (Block cart Store API, classic cart rendering, mini-cart
        // fragments, checkout) read the cart, the product is already in the user's
        // current language. WooCommerce 10.7's CartItemSchema reads `name`,
        // `description`, `sku` directly from `$cart_item['data']->get_title()`
        // etc. — there are no Store API-specific translation hooks for those
        // fields, so the only way to get translated values into Block cart is to
        // present a translated product object.
        //
        // Verified in WC source:
        //   plugins/woocommerce/includes/class-wc-cart-session.php:250
        //   plugins/woocommerce/includes/class-wc-cart.php (apply_filters('woocommerce_add_cart_item', ...))
        add_filter('woocommerce_get_cart_item_from_session', array($this, 'translateCartItemFromSession'), 10, 3);
        add_filter('woocommerce_add_cart_item', array($this, 'translateCartItemOnAdd'), 10, 2);

        // Render-time filters (apply on top of session-load translation as
        // safety nets). Some fire under classic cart only; some fire in Store
        // API too (verified WC 10.7 source):
        //   - woocommerce_cart_item_product   — NOT applied in Block cart
        //   - woocommerce_cart_item_product_id — NOT applied in Block cart
        //   - woocommerce_cart_item_permalink  — IS applied in Store API (CartItemSchema.php:52)
        //   - woocommerce_get_item_data        — IS applied for variation attrs (CartItemSchema.php:169)
        // Keeping the legacy hooks doesn't cause double-translation because
        // pll_get_post(translatedId) is idempotent for the same target language.
        add_filter('woocommerce_cart_item_product', array($this, 'translateCartItemProduct'), 10, 2);
        add_filter('woocommerce_cart_item_product_id', array($this, 'translateCartItemProductId'), 10, 1);
        add_filter('woocommerce_cart_item_permalink', array($this, 'translateCartItemPermalink'), 10, 2);
        add_filter('woocommerce_get_item_data', array($this, 'translateCartItemData'), 10, 2);

        // Language-change cache invalidation: forces cart fragments to refresh
        // when the `pll_language` cookie changes. Works for both classic cart and
        // Block cart (Block cart's Store API responses are also subject to the
        // cart fragment session storage).
        add_action('wp_enqueue_scripts', array($this, 'replaceCartFragmentsScript'), 100);

    }

    /**
     * Translate a cart item to the current language. Idempotent.
     *
     * Mutates the cart item array in place:
     *   - `data` (WC_Product object) → translated product
     *   - `variation` (variation attribute slugs) → translated slugs when the
     *     translated product is a variation
     *
     * Why we DON'T mutate product_id / variation_id / data_hash:
     *   The cart line's KEY (in WC_Cart::cart_contents) is generated by
     *   WC_Cart::generate_cart_id() from the ORIGINAL adding-language IDs and is
     *   used by find_product_in_cart() for dedup lookup. Mutating the IDs would
     *   leave the cart line's stored KEY out of sync with its current internal
     *   IDs, breaking dedup on subsequent adds in different languages. We instead
     *   only translate `data` (display product) and `variation` (display slugs);
     *   downstream consumers (CartItemSchema, classic templates) read from those
     *   fields. The `product_id` / `variation_id` stay as the canonical (original)
     *   IDs, which is also the correct value to record in resulting orders.
     *
     * Other fields (key, quantity, line_subtotal, variation, etc.) are unchanged.
     *
     * If no translation exists for the current language, returns the input
     * unchanged. Safe to call multiple times — subsequent translations of an
     * already-translated product return the same product (Polylang's
     * translation lookup is symmetric).
     *
     * @param array $cart_item Cart item array.
     * @return array Mutated cart item array.
     */
    protected function translateCartItemArray(array $cart_item)
    {
        if (!isset($cart_item['data']) || !$cart_item['data'] instanceof \WC_Product) {
            return $cart_item;
        }
        if (!function_exists('pll_get_post') || !function_exists('pll_current_language')) {
            return $cart_item;
        }
        $current_lang = pll_current_language();
        if (!$current_lang) {
            return $cart_item;
        }

        $product = $cart_item['data'];
        $translated_product = null;

        if ($product->get_type() === 'variation') {
            $variation_id = isset($cart_item['variation_id']) ? (int) $cart_item['variation_id'] : (int) $product->get_id();
            $variation_translation = $this->getVariationTranslation($variation_id, $current_lang);
            if ($variation_translation && $variation_translation->get_id() !== $variation_id) {
                $cart_item['data'] = $variation_translation;
                $translated_product = $variation_translation;
            }
        } else {
            // Simple / grouped / external products.
            $product_id = (int) $product->get_id();
            $translated_id = pll_get_post($product_id, $current_lang);
            if ($translated_id && $translated_id !== $product_id) {
                $translated = wc_get_product($translated_id);
                if ($translated) {
                    $cart_item['data'] = $translated;
                    $translated_product = $translated;
                }
            }
        }

        // Sync $cart_item['variation'] to the translated variation's own attribute
        // slugs. Without this, Store API's CartItemSchema::format_variation_data
        // resolves attribute terms via `get_term_by('slug', $source_lang_slug, ...)`
        // which under Polylang's per-language term filtering may not return the
        // correct term — leaking source-language slugs in the variation field of
        // the Block cart response.
        //
        // The translated WC_Product_Variation has its own attribute slug map
        // (in the target language), exposed via get_variation_attributes(). Use it.
        if ($translated_product
            && $translated_product instanceof \WC_Product_Variation
            && method_exists($translated_product, 'get_variation_attributes')
        ) {
            $translated_attrs = $translated_product->get_variation_attributes();
            if (is_array($translated_attrs) && !empty($translated_attrs)) {
                $cart_item['variation'] = $translated_attrs;
            }
        }

        return $cart_item;
    }

    /**
     * Hook callback: translate cart items as they're restored from session
     * for the current request.
     *
     * Hooked to `woocommerce_get_cart_item_from_session` which fires once per
     * cart item per request, BEFORE Store API serialization runs.
     *
     * @param array  $session_data The cart item array reconstructed from session.
     * @param array  $values       Original session values.
     * @param string $key          Cart item key.
     * @return array
     */
    public function translateCartItemFromSession($session_data, $values, $key)
    {
        return $this->translateCartItemArray($session_data);
    }

    /**
     * Hook callback: translate cart items as they're added to the cart in the
     * current request (so the in-memory cart is correct without waiting for the
     * next session-load).
     *
     * Hooked to `woocommerce_add_cart_item` which fires inside
     * `WC_Cart::add_to_cart()` after the item has been assembled.
     *
     * @param array  $cart_item Cart item array.
     * @param string $cart_item_key Cart item key.
     * @return array
     */
    public function translateCartItemOnAdd($cart_item, $cart_item_key)
    {
        return $this->translateCartItemArray($cart_item);
    }

    /**
     * Add to cart (CLASSIC add path).
     *
     * If a translation of the product being added is already in the cart, this
     * filter swaps the product ID to the existing cart-line product ID so WC's
     * `find_product_in_cart()` matches and quantity is incremented instead of
     * a new cart line being created.
     *
     * Hooked to `woocommerce_add_to_cart_product_id` which is applied by
     * `WC_Cart::add_to_cart()` (classic) but NOT by the Store API. See
     * `dedupeStoreApiAdd()` for the Block cart equivalent.
     *
     * @param int $ID the current product ID
     *
     * @return int the final product ID
     */
    public function addToCart($ID)
    {
        $result = $ID;

        // get the product translations
        $IDS = Utilities::getProductTranslationsArrayByID($ID);
        if (!is_array($IDS)) {
            return $result;
        }

        // Check if any of product's translations is already in cart.
        //
        // CRITICAL: read the cart line's CANONICAL `product_id` (the value used
        // by WC_Cart::generate_cart_id() to compute the line's KEY), NOT
        // `$values['data']->get_id()`. Our session-load filter swaps `$values['data']`
        // to the translated product object, so reading `data->get_id()` returns the
        // current-language ID — which doesn't match the cart line's stored KEY,
        // causing dedup to fail and creating duplicate cart lines on repeat adds
        // across language switches.
        if (WC()->cart) {
            foreach (WC()->cart->get_cart() as $values) {
                $cart_canonical_id = isset($values['product_id']) ? (int) $values['product_id'] : 0;
                if ($cart_canonical_id && in_array($cart_canonical_id, $IDS, true)) {
                    $result = $cart_canonical_id;
                    break;
                }
            }
        }

        return $result;
    }

    /**
     * Add to cart dedup for STORE API (Block cart) add path.
     *
     * The Store API's `CartController::add_to_cart()` computes the cart_id from
     * the request's product/variation ID and then calls `find_product_in_cart`.
     * It does NOT apply `woocommerce_add_to_cart_product_id`. We instead hook
     * `woocommerce_store_api_add_to_cart_data` (added in WC 8.8) which fires
     * BEFORE the cart_id is computed, allowing us to swap the request's `id` to
     * the canonical product ID of an existing cart line for the same logical
     * product (any language).
     *
     * Verified in WC 10.7 source:
     *   src/StoreApi/Routes/V1/CartAddItem.php:116-125
     *   src/StoreApi/Utilities/CartController.php:99-147
     *
     * `POST /wc/store/v1/cart/items` is covered by `dedupeStoreApiCartItemsRoute()`
     * which mutates the REST request `id` before route callbacks run.
     *
     * @param array $add_to_cart_data Filter input: ['id' => int, 'quantity' => int,
     *                                'variation' => array, 'cart_item_data' => array].
     *                                The 'id' is the product ID for simple/grouped/external
     *                                or the variation ID for variations.
     * @param \WP_REST_Request|null $request The original Store API request (unused but kept
     *                                       for filter signature compatibility).
     * @return array Modified $add_to_cart_data with potentially swapped 'id'.
     */
    public function dedupeStoreApiAdd($add_to_cart_data, $request = null)
    {
        if (empty($add_to_cart_data['id']) || !is_numeric($add_to_cart_data['id'])) {
            return $add_to_cart_data;
        }

        $dedup_target = $this->resolveDedupTarget((int) $add_to_cart_data['id']);
        if (null !== $dedup_target) {
            $add_to_cart_data['id'] = $dedup_target;
        }

        return $add_to_cart_data;
    }

    /**
     * Add to cart dedup for STORE API `POST /wc/store/v1/cart/items`.
     *
     * Mutates request `id` before route callback so `CartController::add_to_cart()`
     * receives the canonical cart-line ID and `find_product_in_cart()` dedupes.
     *
     * @param mixed            $response Result to send to the client.
     * @param array            $handler  Route handler.
     * @param \WP_REST_Request $request  REST request object.
     * @return mixed
     */
    public function dedupeStoreApiCartItemsRoute($response, $handler, \WP_REST_Request $request)
    {
        if ('POST' !== $request->get_method() || '/wc/store/v1/cart/items' !== $request->get_route()) {
            return $response;
        }

        $incoming_id = $request->get_param('id');
        if (!is_numeric($incoming_id)) {
            return $response;
        }

        $dedup_target = $this->resolveDedupTarget((int) $incoming_id);
        if (null !== $dedup_target) {
            $request->set_param('id', $dedup_target);
        }

        return $response;
    }

    /**
     * Resolve a canonical in-cart product/variation ID for dedup, if any.
     *
     * @param int $incoming_id Product ID or variation ID being added.
     * @return int|null Canonical in-cart ID to use for dedup, null when not found.
     */
    private function resolveDedupTarget($incoming_id)
    {
        $incoming_id = (int) $incoming_id;
        if ($incoming_id <= 0 || !function_exists('pll_get_post') || !WC()->cart) {
            return null;
        }

        $incoming_product = wc_get_product($incoming_id);
        if (!$incoming_product) {
            return null;
        }

        // For variations, dedup at the variation-sibling level via the
        // `_point_to_variation` meta linkage. Each variation has a meta value
        // pointing to the master variation ID (the original-language one); a
        // master self-references. Translations of the same logical variation
        // share the same master ID.
        if ($incoming_product->get_type() === 'variation') {
            $incoming_master = (int) get_post_meta($incoming_id, Variation::DUPLICATE_KEY, true);
            if (!$incoming_master) {
                // No linkage recorded — can't dedup safely.
                return null;
            }

            foreach (WC()->cart->get_cart() as $values) {
                // Read canonical `variation_id`, not translated `$values['data']->get_id()`.
                $cart_variation_id = isset($values['variation_id']) ? (int) $values['variation_id'] : 0;
                if (!$cart_variation_id) {
                    continue;
                }
                $cart_master = (int) get_post_meta($cart_variation_id, Variation::DUPLICATE_KEY, true);
                if ($cart_master && $cart_master === $incoming_master) {
                    return $cart_variation_id;
                }
            }

            return null;
        }

        // Simple / grouped / external products.
        $translations = Utilities::getProductTranslationsArrayByID($incoming_id);
        if (!is_array($translations) || empty($translations)) {
            return null;
        }

        foreach (WC()->cart->get_cart() as $values) {
            // Use canonical `product_id`, not translated `$values['data']->get_id()`.
            $cart_canonical_id = isset($values['product_id']) ? (int) $values['product_id'] : 0;
            if ($cart_canonical_id && in_array($cart_canonical_id, $translations, true)) {
                return $cart_canonical_id;
            }
        }

        return null;
    }

    /**
     * Translate displayed product in cart.
     *
     * @param \WC_Product|\WC_Product_Variation $cart_item_data
     * @param array                             $cart_item
     *
     * @return \WC_Product|\WC_Product_Variation
     */
    public function translateCartItemProduct($cart_item_data, $cart_item)
    {
        if (!($cart_item_data instanceof \WC_Product)) {
            return $cart_item_data;
        }

        $cart_product_id = isset($cart_item['product_id']) ? (int) $cart_item['product_id'] : 0;
        $cart_variation_id = isset($cart_item['variation_id']) ? (int) $cart_item['variation_id'] : 0;

        // By default, returns the same input
        $cart_item_data_translation = $cart_item_data;

        switch ($cart_item_data->get_type()) {
            case 'variation':
                $variation_translation = $this->getVariationTranslation($cart_variation_id);
                if ($variation_translation && $variation_translation->get_id() !== $cart_variation_id) {
                    $cart_item_data_translation = $variation_translation;
                }
                break;

            case 'simple':
            default:
                $product_translation = Utilities::getProductTranslationByID($cart_product_id);
                if ($product_translation && $product_translation->get_id() !== $cart_product_id) {
                    $cart_item_data_translation = $product_translation;
                }
                break;
        }


        // If we are changing the product to the right language
        if ($cart_item_data_translation->get_id() !== $cart_item_data->get_id()) {
            $cart_item_data_translation = apply_filters(HooksInterface::CART_SWITCHED_ITEM, $cart_item_data_translation, $cart_item_data, $cart_item);
        }

        return $cart_item_data_translation;
    }

    /**
     * Replace products id in cart with id of product translation.
     *
     * @param int   $cart_product_id    Product Id
     *
     * @return int Id of the product translation
     */
    public function translateCartItemProductId($cart_product_id)
    {
        $translation_id = pll_get_post($cart_product_id);
        return $translation_id ? $translation_id : $cart_product_id;
    }

    /**
     * Translate product attributes in the product permalink querystring.
     *
     * @param string    $item_permalink    Product permalink
     * @param array     $cart_item         Cart item
     *
     * @return string   Translated permalink
     */
    public function translateCartItemPermalink($item_permalink, $cart_item)
    {
        $cart_variation_id = isset($cart_item['variation_id']) ? (int) $cart_item['variation_id'] : 0;

        if ($cart_variation_id !== 0) {
            // Variation
            $variation_translation = $this->getVariationTranslation($cart_variation_id);
            return $variation_translation ? $variation_translation->get_permalink() : $item_permalink;
        }

        return $item_permalink;
    }

    /**
     * Translate product variation attributes.
     *
     * Known limitation: `get_term_by('slug', ...)` returns the first matching
     * term. Under Polylang's per-language taxonomy filtering this can be
     * context-dependent. The safer Block-cart path is the variation-slug sync in
     * `translateCartItemArray()` which reads the translated variation's own
     * attribute slugs via `WC_Product_Variation::get_variation_attributes()`.
     * This classic-cart path is retained for shortcode-rendering back-compat.
     *
     * @param array     $item_data      Variation attributes
     * @param array     $cart_item      Cart item
     *
     * @return array   Translated attributes
     */
    public function translateCartItemData($item_data, $cart_item)
    {
        // We don't translate the variation attributes if the product in the cart
        // is not a product variation, and in case of a product variation, it
        // doesn't have a translation in the current language.
        $cart_variation_id = isset($cart_item['variation_id']) ? (int) $cart_item['variation_id'] : 0;

        if ($cart_variation_id === 0) {
            // Not a variation product
            return $item_data;
        } elseif ($this->getVariationTranslation($cart_variation_id) === false) {
            // Variation product without translation in current language
            return $item_data;
        }

        if (!isset($cart_item['variation']) || !is_array($cart_item['variation'])) {
            return $item_data;
        }

        $item_data_translation = array();

        foreach ($item_data as $data) {
            if (!isset($data['key']) || !isset($data['value'])) {
                $item_data_translation[] = $data;
                continue;
            }

            $term_id = null;

            foreach ($cart_item['variation'] as $tax => $term_slug) {
                $tax = str_replace('attribute_', '', $tax);
                $term = get_term_by('slug', $term_slug, $tax);

                if ($term && $term->name === $data['value']) {
                    $term_id = $term->term_id;
                    break;
                }
            }

            if ($term_id !== 0 && $term_id !== null) {
                // Product attribute is a taxonomy term - check if Polylang has a translation
                $term_id_translation = pll_get_term($term_id);

                if ($term_id_translation == $term_id) {
                    // Already showing the attribute (term) in the correct language
                    $item_data_translation[] = $data;
                } else {
                    // Get term translation from id
                    $term_translation = get_term($term_id_translation);
                    $item_data_translation[] = array(
                        'key' => $data['key'],
                        'value' => !is_wp_error($term_translation) ? $term_translation->name : $data['value'],
                    ); // On error return same
                }
            } else {
                // Product attribute is post metadata and not translatable - return same
                $item_data_translation[] = $data;
            }
        }

        return !empty($item_data_translation) ? $item_data_translation : $item_data;
    }

    /**
     * Add a Polylang language-change detection layer on top of WooCommerce's native cart
     * fragments script.
     *
     * v1.x of this plugin replaced wc-cart-fragments wholesale with a forked copy that
     * carried a stale clone of WooCommerce's code plus one Polylang-specific addition.
     * That approach has been removed in favour of leaving wc-cart-fragments alone and
     * shipping only the small adapter script that triggers a fragment refresh when
     * the `pll_language` cookie changes.
     *
     * Note: jquery-cookie is not used. The adapter script uses native document.cookie.
     */
    public function replaceCartFragmentsScript()
    {
        // Adapter script is small enough that maintaining a minified twin is not worth
        // the pre-build complexity for an "occasional updates" maintenance model.
        wp_enqueue_script(
            'wpi-cart-language',
            plugins_url('public/js/Cart.js', Hyyan_WPI_DIR),
            array('jquery'),
            Plugin::getVersion(),
            true
        );
    }

    /**
     * Get product variation translation.
     *
     * Returns the product variation object for a given language.
     *
     * @param int       $variation_id   (required) Id of the variation to translate
     * @param string    $lang           (optional) 2-letters code of the language
     *                                  like Polylang
     *                                  language slugs, defaults to current language
     *
     * @return \WP_Product_Variation    Product variation object for the given
     *                                  language, false on error or if doesn't exists.
     */
    public function getVariationTranslation($variation_id, $lang = '')
    {
        $_variation = false;

        // Get parent product translation id for the given language
        $variation = wc_get_product($variation_id);
        $parentid = Utilities::get_variation_parentid($variation);
        $_product_id = pll_get_post($parentid, $lang);

        // Get variation translation using the duplication metadata value
        $meta = get_post_meta($variation_id, Variation::DUPLICATE_KEY, true);

        if ($_product_id && $meta) {
            // Get posts (variations) with duplication metadata value
            $variation_post = get_posts(array(
                'meta_key' => Variation::DUPLICATE_KEY,
                'meta_value' => $meta,
                'post_type' => 'product_variation',
                'post_parent' => $_product_id
            ));

            // Get variation translation
            if ($variation_post && count($variation_post) == 1) {
                $_variation = wc_get_product($variation_post[0]->ID);
            }
        }

        return $_variation;
    }
}
